### ISSUE TITLE
Option to put vertical separator line in tablet mode

### ISSUE THREAD

**Issue by jrcacd** [saurabharora90/OnePreference#3]
Could this be done?

![screenshot](https://user-images.githubusercontent.com/26005662/27221091-4921b638-527f-11e7-9cce-34c6fa5f57d6.png)

**Comment by jrcacd** [comment]
???

**Comment by saurabharora90** [comment]
Yes this should be possible. Check out the [Custom Layout Sample](https://github.com/saurabharora90/OnePreference/blob/master/sample/src/main/java/com/sa90/onepreferencedemo/CustomLayoutActivity.java) and it's [UI](https://github.com/saurabharora90/OnePreference/blob/master/sample/src/main/res/layout-sw600dp/content_custom_layout.xml).

You can customize the UI to add the vertical separator.
